app:
  config-home: ${APP_HOME}/${spring.application.name}/config

spring:
  application:
    name: com.example.springboot
  thymeleaf:
    prefix: file:${APP_HOME}/${spring.application.name}/views/
    check-template: true
  resources:
    static-locations: file:${APP_HOME}/${spring.application.name}/resources/
  mvc:
    static-path-pattern: /resources/**
  h2:
    console:
      enabled: true
      
server:
  port: 9090
  
management:
  context-path: /manage
  security:
    enabled: false
    
logging:
  config: ${app.config-home}/logback.xml
 
liquibase:
  change-log: file:${app.config-home}/liquibase/db.changelog-master.xml
  parameters:
    liquibase-home: ${app.config-home}/liquibase